user1 = User.create(email: 'Bob@gmail.com', first_name: 'Bob', last_name: 'Smith', password: 'password')
user2 = User.create(email: 'Jill@gmail.com', first_name: 'Jill', last_name: 'Finch', password: 'password')
user3 = User.create(email: 'user', first_name: 'Hank', last_name: 'Park', password: 'user')
admin = User.create(email: 'admin', first_name: 'JP', last_name: 'Lynch', password: 'admin', role: 1)

q1 = user1.questions.create(content: 'How do people train for a marathon?')
q2 = user1.questions.create(content: 'How do people eat 10 pizzas?')
q3 = user1.questions.create(content: 'Why is the sky blue?')
a3 = admin.answers.create(content: 'Because it is.', question_id: 3)
q4 = user2.questions.create(content: 'Why does coffee taste so good?')
q5 = user2.questions.create(content: 'How long does it take to drive to NJ?')
q6 = user2.questions.create(content: 'Where in the world is Paul?')
q7 = user3.questions.create(content: 'How far away is the moon?')
q8 = user3.questions.create(content: 'How many pounds is 100L of water?')
q9 = user3.questions.create(content: 'Does pineapple belong on pizza?')
